//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponentLib.Controls {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComponentLib.Controls.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить из интернета.
        /// </summary>
        internal static string Addinternet {
            get {
                return ResourceManager.GetString("Addinternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Числа Аэгеан.
        /// </summary>
        internal static string AegeanNumbers {
            get {
                return ResourceManager.GetString("AegeanNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Африканские.
        /// </summary>
        internal static string African {
            get {
                return ResourceManager.GetString("African", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алфавитные формы представления.
        /// </summary>
        internal static string AlphabeticPresentationForms {
            get {
                return ResourceManager.GetString("AlphabeticPresentationForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Древнегреческая музыкальная нотация.
        /// </summary>
        internal static string AncientGreekMusicalNotation {
            get {
                return ResourceManager.GetString("AncientGreekMusicalNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Древнегреческие цифры.
        /// </summary>
        internal static string AncientGreekNumbers {
            get {
                return ResourceManager.GetString("AncientGreekNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Арабское письмо.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формы представления арабских букв-A.
        /// </summary>
        internal static string ArabicPresentationFormsA {
            get {
                return ResourceManager.GetString("ArabicPresentationFormsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формы представления арабских букв-B.
        /// </summary>
        internal static string ArabicPresentationFormsB {
            get {
                return ResourceManager.GetString("ArabicPresentationFormsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные символы арабского письма.
        /// </summary>
        internal static string ArabicSupplement {
            get {
                return ResourceManager.GetString("ArabicSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Армянский алфавит.
        /// </summary>
        internal static string Armenian {
            get {
                return ResourceManager.GetString("Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стрелки.
        /// </summary>
        internal static string Arrows {
            get {
                return ResourceManager.GetString("Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Балийская письменность.
        /// </summary>
        internal static string Balinese {
            get {
                return ResourceManager.GetString("Balinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бамумская.
        /// </summary>
        internal static string Bamum {
            get {
                return ResourceManager.GetString("Bamum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная латиница.
        /// </summary>
        internal static string BasicLatin {
            get {
                return ResourceManager.GetString("BasicLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бенгальская письменность.
        /// </summary>
        internal static string Bengali {
            get {
                return ResourceManager.GetString("Bengali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы заполнения.
        /// </summary>
        internal static string BlockElements {
            get {
                return ResourceManager.GetString("BlockElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бопомофо.
        /// </summary>
        internal static string Bopomofo {
            get {
                return ResourceManager.GetString("Bopomofo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенный набор символов бопомофо.
        /// </summary>
        internal static string BopomofoExtended {
            get {
                return ResourceManager.GetString("BopomofoExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы рисования рамок.
        /// </summary>
        internal static string BoxDrawing {
            get {
                return ResourceManager.GetString("BoxDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Азбука Брайля.
        /// </summary>
        internal static string BraillePatterns {
            get {
                return ResourceManager.GetString("BraillePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бугийская письменность.
        /// </summary>
        internal static string Buginese {
            get {
                return ResourceManager.GetString("Buginese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бухид.
        /// </summary>
        internal static string Buhid {
            get {
                return ResourceManager.GetString("Buhid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Византийские музыкальные символы.
        /// </summary>
        internal static string ByzantineMusicalSymbols {
            get {
                return ResourceManager.GetString("ByzantineMusicalSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центрально-Азиатские.
        /// </summary>
        internal static string CentralAsian {
            get {
                return ResourceManager.GetString("CentralAsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чамская.
        /// </summary>
        internal static string Cham {
            get {
                return ResourceManager.GetString("Cham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность чероки.
        /// </summary>
        internal static string Cherokee {
            get {
                return ResourceManager.GetString("Cherokee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки совместимости ККЯ.
        /// </summary>
        internal static string CJKCompatibility {
            get {
                return ResourceManager.GetString("CJKCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формы совместимости ККЯ.
        /// </summary>
        internal static string CJKCompatibilityForms {
            get {
                return ResourceManager.GetString("CJKCompatibilityForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Совместимые иероглифы ККЯ.
        /// </summary>
        internal static string CJKCompatibilityIdeographs {
            get {
                return ResourceManager.GetString("CJKCompatibilityIdeographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные иероглифические ключи ККЯ.
        /// </summary>
        internal static string CJKRadicalsSupplement {
            get {
                return ResourceManager.GetString("CJKRadicalsSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черты ККЯ.
        /// </summary>
        internal static string CJKStrokes {
            get {
                return ResourceManager.GetString("CJKStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы и пунктуация ККЯ.
        /// </summary>
        internal static string CJKSymbolsAndPunctuation {
            get {
                return ResourceManager.GetString("CJKSymbolsAndPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Унифицированные иероглифы ККЯ.
        /// </summary>
        internal static string CJKUnifiedIdeographs {
            get {
                return ResourceManager.GetString("CJKUnifiedIdeographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Унифицированные иероглифы ККЯ (расширение A).
        /// </summary>
        internal static string CJKUnifiedIdeographsExtensionA {
            get {
                return ResourceManager.GetString("CJKUnifiedIdeographsExtensionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диакритические знаки.
        /// </summary>
        internal static string CombiningDiacriticalMarks {
            get {
                return ResourceManager.GetString("CombiningDiacriticalMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комбинируемые диакритические знаки для символов.
        /// </summary>
        internal static string CombiningDiacriticalMarksForSymbols {
            get {
                return ResourceManager.GetString("CombiningDiacriticalMarksForSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допонительные комбинируемые диакритические знаки лоя символов.
        /// </summary>
        internal static string CombiningDiacriticalMarksSupplement {
            get {
                return ResourceManager.GetString("CombiningDiacriticalMarksSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комбинируемые половинки символов.
        /// </summary>
        internal static string CombiningHalfMarks {
            get {
                return ResourceManager.GetString("CombiningHalfMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общепринятые формы индийских цифр.
        /// </summary>
        internal static string CommonIndicNumberForms {
            get {
                return ResourceManager.GetString("CommonIndicNumberForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значки управляющих кодов.
        /// </summary>
        internal static string ControlPictures {
            get {
                return ResourceManager.GetString("ControlPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коптский алфавит.
        /// </summary>
        internal static string Coptic {
            get {
                return ResourceManager.GetString("Coptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счётные палочки.
        /// </summary>
        internal static string CountingRodNumerals {
            get {
                return ResourceManager.GetString("CountingRodNumerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы валют.
        /// </summary>
        internal static string CurrencySymbols {
            get {
                return ResourceManager.GetString("CurrencySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слоги киприотов.
        /// </summary>
        internal static string CypriotSyllabary {
            get {
                return ResourceManager.GetString("CypriotSyllabary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кириллица.
        /// </summary>
        internal static string Cyrillic {
            get {
                return ResourceManager.GetString("Cyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кириллица (расширение A).
        /// </summary>
        internal static string CyrillicExtendedA {
            get {
                return ResourceManager.GetString("CyrillicExtendedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кириллица (расширение B).
        /// </summary>
        internal static string CyrillicExtendedB {
            get {
                return ResourceManager.GetString("CyrillicExtendedB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные символы кириллицы.
        /// </summary>
        internal static string CyrillicSupplement {
            get {
                return ResourceManager.GetString("CyrillicSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деванагари.
        /// </summary>
        internal static string Devanagari {
            get {
                return ResourceManager.GetString("Devanagari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деванагари (расширение).
        /// </summary>
        internal static string DevanagariExtended {
            get {
                return ResourceManager.GetString("DevanagariExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диакритические знаки.
        /// </summary>
        internal static string Diacritic {
            get {
                return ResourceManager.GetString("Diacritic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки орнамента.
        /// </summary>
        internal static string Dingbats {
            get {
                return ResourceManager.GetString("Dingbats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восточно-Азиатские.
        /// </summary>
        internal static string EastAsian {
            get {
                return ResourceManager.GetString("EastAsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вложенные буквы и цифры.
        /// </summary>
        internal static string EnclosedAlphanumerics {
            get {
                return ResourceManager.GetString("EnclosedAlphanumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вложенные буквы и месяцы ККЯ.
        /// </summary>
        internal static string EnclosedCJKLettersAndMonths {
            get {
                return ResourceManager.GetString("EnclosedCJKLettersAndMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эфиопская слоговая письменность.
        /// </summary>
        internal static string Ethiopic {
            get {
                return ResourceManager.GetString("Ethiopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенный набор символов эфиопского письма.
        /// </summary>
        internal static string EthiopicExtended {
            get {
                return ResourceManager.GetString("EthiopicExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные символы эфиопской письменности.
        /// </summary>
        internal static string EthiopicSupplement {
            get {
                return ResourceManager.GetString("EthiopicSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Европейские.
        /// </summary>
        internal static string European {
            get {
                return ResourceManager.GetString("European", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаки пунктуации.
        /// </summary>
        internal static string GeneralPunctuation {
            get {
                return ResourceManager.GetString("GeneralPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Геометрические фигуры.
        /// </summary>
        internal static string GeometricShapes {
            get {
                return ResourceManager.GetString("GeometricShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузинский алфавит.
        /// </summary>
        internal static string Georgian {
            get {
                return ResourceManager.GetString("Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные символы грузинского алфавита.
        /// </summary>
        internal static string GeorgianSupplement {
            get {
                return ResourceManager.GetString("GeorgianSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глаголица.
        /// </summary>
        internal static string Glagolitic {
            get {
                return ResourceManager.GetString("Glagolitic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готский.
        /// </summary>
        internal static string Gothic {
            get {
                return ResourceManager.GetString("Gothic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Греческий и коптский алфавиты.
        /// </summary>
        internal static string GreekAndCoptic {
            get {
                return ResourceManager.GetString("GreekAndCoptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенные набор символов греческого алфавита.
        /// </summary>
        internal static string GreekExtended {
            get {
                return ResourceManager.GetString("GreekExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гуджарати.
        /// </summary>
        internal static string Gujarati {
            get {
                return ResourceManager.GetString("Gujarati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гурмукхи.
        /// </summary>
        internal static string Gurmukhi {
            get {
                return ResourceManager.GetString("Gurmukhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полуширинные и полноширинные формы.
        /// </summary>
        internal static string HalfwidthAndFullwidthForms {
            get {
                return ResourceManager.GetString("HalfwidthAndFullwidthForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чамо, комбинируемое с хангылем.
        /// </summary>
        internal static string HangulCompatibilityJamo {
            get {
                return ResourceManager.GetString("HangulCompatibilityJamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хангыль.
        /// </summary>
        internal static string HangulJamo {
            get {
                return ResourceManager.GetString("HangulJamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хангыль (расширение A).
        /// </summary>
        internal static string HangulJamoExtendedA {
            get {
                return ResourceManager.GetString("HangulJamoExtendedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хангыль (расширение B).
        /// </summary>
        internal static string HangulJamoExtendedB {
            get {
                return ResourceManager.GetString("HangulJamoExtendedB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слоги хангыля.
        /// </summary>
        internal static string HangulSyllables {
            get {
                return ResourceManager.GetString("HangulSyllables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хануноо.
        /// </summary>
        internal static string Hanunoo {
            get {
                return ResourceManager.GetString("Hanunoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иврит.
        /// </summary>
        internal static string Hebrew {
            get {
                return ResourceManager.GetString("Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хирагана.
        /// </summary>
        internal static string Hiragana {
            get {
                return ResourceManager.GetString("Hiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы описания иероглифов.
        /// </summary>
        internal static string IdeographicDescriptionCharacters {
            get {
                return ResourceManager.GetString("IdeographicDescriptionCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите значение.
        /// </summary>
        internal static string InputValue {
            get {
                return ResourceManager.GetString("InputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенный набор IPA.
        /// </summary>
        internal static string IPAExtensions {
            get {
                return ResourceManager.GetString("IPAExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яванская письменность.
        /// </summary>
        internal static string Javanese {
            get {
                return ResourceManager.GetString("Javanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канбун.
        /// </summary>
        internal static string Kanbun {
            get {
                return ResourceManager.GetString("Kanbun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иероглифические ключи словаря Канси.
        /// </summary>
        internal static string KangxiRadicals {
            get {
                return ResourceManager.GetString("KangxiRadicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каннада.
        /// </summary>
        internal static string Kannada {
            get {
                return ResourceManager.GetString("Kannada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Катагана.
        /// </summary>
        internal static string Katakana {
            get {
                return ResourceManager.GetString("Katakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фонетические расширения катаканы.
        /// </summary>
        internal static string KatakanaPhoneticExtensions {
            get {
                return ResourceManager.GetString("KatakanaPhoneticExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность кайя.
        /// </summary>
        internal static string KayahLi {
            get {
                return ResourceManager.GetString("KayahLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кхмерская письменность.
        /// </summary>
        internal static string Khmer {
            get {
                return ResourceManager.GetString("Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кхмерские символы.
        /// </summary>
        internal static string KhmerSymbols {
            get {
                return ResourceManager.GetString("KhmerSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лаосская письменность.
        /// </summary>
        internal static string Lao {
            get {
                return ResourceManager.GetString("Lao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнение латиницы 1.
        /// </summary>
        internal static string Latin1Supplement {
            get {
                return ResourceManager.GetString("Latin1Supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенная латиница-A.
        /// </summary>
        internal static string LatinExtendedA {
            get {
                return ResourceManager.GetString("LatinExtendedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная расширенная латиница.
        /// </summary>
        internal static string LatinExtendedAdditional {
            get {
                return ResourceManager.GetString("LatinExtendedAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенная латиница-B.
        /// </summary>
        internal static string LatinExtendedB {
            get {
                return ResourceManager.GetString("LatinExtendedB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенная латиница-C.
        /// </summary>
        internal static string LatinExtendedC {
            get {
                return ResourceManager.GetString("LatinExtendedC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенная латиница-D.
        /// </summary>
        internal static string LatinExtendedD {
            get {
                return ResourceManager.GetString("LatinExtendedD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лепча.
        /// </summary>
        internal static string Lepcha {
            get {
                return ResourceManager.GetString("Lepcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буквообразные символы.
        /// </summary>
        internal static string LetterlikeSymbols {
            get {
                return ResourceManager.GetString("LetterlikeSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пиьсменность лимбу.
        /// </summary>
        internal static string Limbu {
            get {
                return ResourceManager.GetString("Limbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линейный B идеограммы.
        /// </summary>
        internal static string LinearBIdeograms {
            get {
                return ResourceManager.GetString("LinearBIdeograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линейный B слоги.
        /// </summary>
        internal static string LinearBSyllabary {
            get {
                return ResourceManager.GetString("LinearBSyllabary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Список...).
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность лису.
        /// </summary>
        internal static string Lisu {
            get {
                return ResourceManager.GetString("Lisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Малаялам.
        /// </summary>
        internal static string Malayalam {
            get {
                return ResourceManager.GetString("Malayalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Математические алфавитно-цифровые символы.
        /// </summary>
        internal static string MathematicalAlphanumericSymbols {
            get {
                return ResourceManager.GetString("MathematicalAlphanumericSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Математические операторы.
        /// </summary>
        internal static string MathematicalOperators {
            get {
                return ResourceManager.GetString("MathematicalOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Математические символы.
        /// </summary>
        internal static string Mathematics {
            get {
                return ResourceManager.GetString("Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность манипури.
        /// </summary>
        internal static string MeeteiMayek {
            get {
                return ResourceManager.GetString("MeeteiMayek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ближневосточные.
        /// </summary>
        internal static string MiddleEast {
            get {
                return ResourceManager.GetString("MiddleEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разнообразные математические символы-A.
        /// </summary>
        internal static string MiscellaneousMathematicalSymbolsA {
            get {
                return ResourceManager.GetString("MiscellaneousMathematicalSymbolsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разнообразные математические символы-B.
        /// </summary>
        internal static string MiscellaneousMathematicalSymbolsB {
            get {
                return ResourceManager.GetString("MiscellaneousMathematicalSymbolsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разнообразные символы.
        /// </summary>
        internal static string MiscellaneousSymbols {
            get {
                return ResourceManager.GetString("MiscellaneousSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разнообразные символы и стрелки.
        /// </summary>
        internal static string MiscellaneousSymbolsAndArrows {
            get {
                return ResourceManager.GetString("MiscellaneousSymbolsAndArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разнообразные технические символы.
        /// </summary>
        internal static string MiscellaneousTechnical {
            get {
                return ResourceManager.GetString("MiscellaneousTechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы изменения тона.
        /// </summary>
        internal static string ModifierToneLetters {
            get {
                return ResourceManager.GetString("ModifierToneLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старомонгольская письменность.
        /// </summary>
        internal static string Mongolian {
            get {
                return ResourceManager.GetString("Mongolian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Музыкальные символы.
        /// </summary>
        internal static string MusicalSymbols {
            get {
                return ResourceManager.GetString("MusicalSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мьянманская письменность.
        /// </summary>
        internal static string Myanmar {
            get {
                return ResourceManager.GetString("Myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мьянманская письменность (расширение A).
        /// </summary>
        internal static string MyanmarExtendedA {
            get {
                return ResourceManager.GetString("MyanmarExtendedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый алфавит тай лы.
        /// </summary>
        internal static string NewTaiLue {
            get {
                return ResourceManager.GetString("NewTaiLue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нко.
        /// </summary>
        internal static string NKo {
            get {
                return ResourceManager.GetString("NKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Числовые формы.
        /// </summary>
        internal static string NumberForms {
            get {
                return ResourceManager.GetString("NumberForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Огам.
        /// </summary>
        internal static string Ogham {
            get {
                return ResourceManager.GetString("Ogham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алфавит сантали.
        /// </summary>
        internal static string OlChiki {
            get {
                return ResourceManager.GetString("OlChiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старый итальянский.
        /// </summary>
        internal static string OldItalic {
            get {
                return ResourceManager.GetString("OldItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старый персидский.
        /// </summary>
        internal static string OldPersian {
            get {
                return ResourceManager.GetString("OldPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы оптического распознования.
        /// </summary>
        internal static string OpticalCharacterRecognition {
            get {
                return ResourceManager.GetString("OpticalCharacterRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ория.
        /// </summary>
        internal static string Oriya {
            get {
                return ResourceManager.GetString("Oriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Османский.
        /// </summary>
        internal static string Osmanya {
            get {
                return ResourceManager.GetString("Osmanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие языки.
        /// </summary>
        internal static string OtherLanguages {
            get {
                return ResourceManager.GetString("OtherLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квадратное письмо Пагба-ламы.
        /// </summary>
        internal static string Phags_pa {
            get {
                return ResourceManager.GetString("Phags-pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Филиппинские.
        /// </summary>
        internal static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Финикийский.
        /// </summary>
        internal static string Phoenician {
            get {
                return ResourceManager.GetString("Phoenician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фонетические символы.
        /// </summary>
        internal static string Phonetic {
            get {
                return ResourceManager.GetString("Phonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фонетические расширения.
        /// </summary>
        internal static string PhoneticExtensions {
            get {
                return ResourceManager.GetString("PhoneticExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допонительные фонетические расширения.
        /// </summary>
        internal static string PhoneticExtensionsSupplement {
            get {
                return ResourceManager.GetString("PhoneticExtensionsSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Область для частного использования.
        /// </summary>
        internal static string PrivateUseArea {
            get {
                return ResourceManager.GetString("PrivateUseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность реджанг.
        /// </summary>
        internal static string Rejang {
            get {
                return ResourceManager.GetString("Rejang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руническая письменность.
        /// </summary>
        internal static string Runic {
            get {
                return ResourceManager.GetString("Runic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самаритянская письменность.
        /// </summary>
        internal static string Samaritan {
            get {
                return ResourceManager.GetString("Samaritan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность саураштра.
        /// </summary>
        internal static string Saurashtra {
            get {
                return ResourceManager.GetString("Saurashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сингальская письменность.
        /// </summary>
        internal static string Sinhala {
            get {
                return ResourceManager.GetString("Sinhala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Варианты малого размера.
        /// </summary>
        internal static string SmallFormVariants {
            get {
                return ResourceManager.GetString("SmallFormVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Южной Азии.
        /// </summary>
        internal static string SouthAsian {
            get {
                return ResourceManager.GetString("SouthAsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юго-Восточной Азии.
        /// </summary>
        internal static string SouthEastAsian {
            get {
                return ResourceManager.GetString("SouthEastAsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модификаторы.
        /// </summary>
        internal static string SpacingModifierLetters {
            get {
                return ResourceManager.GetString("SpacingModifierLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специальные символы.
        /// </summary>
        internal static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суданский.
        /// </summary>
        internal static string Sundanese {
            get {
                return ResourceManager.GetString("Sundanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надстрочные и подстрочные знаки.
        /// </summary>
        internal static string SuperscriptsAndSubscripts {
            get {
                return ResourceManager.GetString("SuperscriptsAndSubscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные стрелки-A.
        /// </summary>
        internal static string SupplementalArrowsA {
            get {
                return ResourceManager.GetString("SupplementalArrowsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные стрелки-B.
        /// </summary>
        internal static string SupplementalArrowsB {
            get {
                return ResourceManager.GetString("SupplementalArrowsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные математические операторы.
        /// </summary>
        internal static string SupplementalMathematicalOperators {
            get {
                return ResourceManager.GetString("SupplementalMathematicalOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительные знаки пунктуации.
        /// </summary>
        internal static string SupplementalPunctuation {
            get {
                return ResourceManager.GetString("SupplementalPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Силоти Нагри.
        /// </summary>
        internal static string SylotiNagri {
            get {
                return ResourceManager.GetString("SylotiNagri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы.
        /// </summary>
        internal static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сирийский алфавит.
        /// </summary>
        internal static string Syriac {
            get {
                return ResourceManager.GetString("Syriac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тагальская письменность.
        /// </summary>
        internal static string Tagalog {
            get {
                return ResourceManager.GetString("Tagalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тагбанва.
        /// </summary>
        internal static string Tagbanwa {
            get {
                return ResourceManager.GetString("Tagbanwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность тай лы.
        /// </summary>
        internal static string TaiLe {
            get {
                return ResourceManager.GetString("TaiLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тай Тхам.
        /// </summary>
        internal static string TaiTham {
            get {
                return ResourceManager.GetString("TaiTham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тай Вьет.
        /// </summary>
        internal static string TaiViet {
            get {
                return ResourceManager.GetString("TaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символы Тай Хуан Джинг.
        /// </summary>
        internal static string TaiXuanJingSymbols {
            get {
                return ResourceManager.GetString("TaiXuanJingSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тамильская письменность.
        /// </summary>
        internal static string Tamil {
            get {
                return ResourceManager.GetString("Tamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телугу.
        /// </summary>
        internal static string Telugu {
            get {
                return ResourceManager.GetString("Telugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тана.
        /// </summary>
        internal static string Thaana {
            get {
                return ResourceManager.GetString("Thaana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайская письменность.
        /// </summary>
        internal static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тибетская письменность.
        /// </summary>
        internal static string Tibetan {
            get {
                return ResourceManager.GetString("Tibetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тифинаг.
        /// </summary>
        internal static string Tifinagh {
            get {
                return ResourceManager.GetString("Tifinagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угиратский.
        /// </summary>
        internal static string Ugaritic {
            get {
                return ResourceManager.GetString("Ugaritic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канадское слоговое письмо.
        /// </summary>
        internal static string UnifiedCanadianAboriginalSyllabics {
            get {
                return ResourceManager.GetString("UnifiedCanadianAboriginalSyllabics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенное канадское слоговое письмо.
        /// </summary>
        internal static string UnifiedCanadianAboriginalSyllabicsExtended {
            get {
                return ResourceManager.GetString("UnifiedCanadianAboriginalSyllabicsExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письменность ваи.
        /// </summary>
        internal static string Vai {
            get {
                return ResourceManager.GetString("Vai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Селекторы вариантов начертания.
        /// </summary>
        internal static string VariationSelectors {
            get {
                return ResourceManager.GetString("VariationSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведический расширения.
        /// </summary>
        internal static string VedicExtensions {
            get {
                return ResourceManager.GetString("VedicExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вертикальные формы.
        /// </summary>
        internal static string VerticalForms {
            get {
                return ResourceManager.GetString("VerticalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гексаграммы Ицзин.
        /// </summary>
        internal static string YijingHexagramSymbols {
            get {
                return ResourceManager.GetString("YijingHexagramSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иероглифические ключи письма и.
        /// </summary>
        internal static string YiRadicals {
            get {
                return ResourceManager.GetString("YiRadicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слоги письма и.
        /// </summary>
        internal static string YiSyllables {
            get {
                return ResourceManager.GetString("YiSyllables", resourceCulture);
            }
        }
    }
}
